import { Employee, Department, Position, AuditLog, RoleCapabilityGroup, RoleMeta } from './types';

export const initialDepartments: Department[] = [
  { id: 1, name: 'Executive & Management', code: 'EXEC' },
  { id: 2, name: 'Human Resources', code: 'HR' },
  { id: 3, name: 'Engineering & Technology', code: 'ENG' },
  { id: 4, name: 'Finance & Accounting', code: 'FIN' },
  { id: 5, name: 'Operations & Logistics', code: 'OPS' },
  { id: 6, name: 'Marketing & Sales', code: 'MKT' },
];

export const initialPositions: Position[] = [
  { id: 1, department_id: 1, title: 'Chief Executive Officer' },
  { id: 2, department_id: 2, title: 'HR Director' },
  { id: 3, department_id: 2, title: 'HR Officer' },
  { id: 4, department_id: 3, title: 'Lead Software Architect' },
  { id: 5, department_id: 3, title: 'Senior Full Stack Engineer' },
  { id: 6, department_id: 4, title: 'Senior Financial Controller' },
  { id: 7, department_id: 5, title: 'Operations Supervisor' },
];

export const initialEmployees: Employee[] = [
  {
    id: 1,
    employee_id: 'NDS-00001',
    user_id: 1,
    first_name: 'Tariq',
    last_name: 'Al-Mansoor',
    full_name: 'Tariq Al-Mansoor',
    email: 'tariq.mansoor@nds-hr.corp',
    phone: '+966 11 458 9201',
    mobile: '+966 50 123 4567',
    national_id: '1092837465',
    date_of_birth: '1988-04-12',
    gender: 'male',
    hire_date: '2023-01-15',
    department_id: 2,
    department_name: 'Human Resources',
    position_id: 2,
    position_title: 'HR Director',
    employment_status: 'active',
    basic_salary: 18500.0,
    emergency_contact_name: 'Fatima Al-Mansoor',
    emergency_contact_phone: '+966 55 987 6543',
    emergency_contact_relationship: 'Spouse',
    address: 'King Fahd Road, Al Olaya, Riyadh, Saudi Arabia',
    profile_photo_url: '',
    created_at: '2023-01-15 09:00:00',
  },
  {
    id: 2,
    employee_id: 'NDS-00002',
    user_id: 2,
    first_name: 'Sarah',
    last_name: 'Jenkins',
    full_name: 'Sarah Jenkins',
    email: 'sarah.jenkins@nds-hr.corp',
    phone: '+966 11 458 9202',
    mobile: '+966 54 234 5678',
    national_id: '2983746510',
    date_of_birth: '1992-07-23',
    gender: 'female',
    hire_date: '2023-03-01',
    department_id: 3,
    department_name: 'Engineering & Technology',
    position_id: 4,
    position_title: 'Lead Software Architect',
    employment_status: 'active',
    basic_salary: 22000.0,
    emergency_contact_name: 'David Jenkins',
    emergency_contact_phone: '+966 54 987 1122',
    emergency_contact_relationship: 'Brother',
    address: 'Prince Turki Ibn Abdulaziz Al Awwal St, Riyadh',
    profile_photo_url: '',
    created_at: '2023-03-01 09:00:00',
  },
  {
    id: 3,
    employee_id: 'NDS-00003',
    user_id: 3,
    first_name: 'Fahad',
    last_name: 'Al-Otaibi',
    full_name: 'Fahad Al-Otaibi',
    email: 'fahad.otaibi@nds-hr.corp',
    phone: '+966 11 458 9203',
    mobile: '+966 56 345 6789',
    national_id: '1029384756',
    date_of_birth: '1995-11-05',
    gender: 'male',
    hire_date: '2023-06-10',
    department_id: 2,
    department_name: 'Human Resources',
    position_id: 3,
    position_title: 'HR Officer',
    employment_status: 'active',
    basic_salary: 11500.0,
    emergency_contact_name: 'Saud Al-Otaibi',
    emergency_contact_phone: '+966 56 111 2233',
    emergency_contact_relationship: 'Father',
    address: 'Al Malqa District, Riyadh, Saudi Arabia',
    profile_photo_url: '',
    created_at: '2023-06-10 09:00:00',
  },
  {
    id: 4,
    employee_id: 'NDS-00004',
    user_id: 4,
    first_name: 'Nouf',
    last_name: 'Al-Zahrani',
    full_name: 'Nouf Al-Zahrani',
    email: 'nouf.zahrani@nds-hr.corp',
    phone: '+966 11 458 9204',
    mobile: '+966 55 456 7890',
    national_id: '2093847561',
    date_of_birth: '1994-02-18',
    gender: 'female',
    hire_date: '2023-08-15',
    department_id: 4,
    department_name: 'Finance & Accounting',
    position_id: 6,
    position_title: 'Senior Financial Controller',
    employment_status: 'active',
    basic_salary: 16000.0,
    emergency_contact_name: 'Mona Al-Zahrani',
    emergency_contact_phone: '+966 55 222 3344',
    emergency_contact_relationship: 'Sister',
    address: 'Al Nakheel, Riyadh, Saudi Arabia',
    profile_photo_url: '',
    created_at: '2023-08-15 09:00:00',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 1,
    user_id: 1,
    actor_name: 'Tariq Al-Mansoor',
    action: 'plugin_activated',
    entity_type: 'system',
    entity_id: 1,
    old_values: null,
    new_values: { version: '1.0.0', db_version: '1.0.0', status: 'initialized' },
    ip_address: '127.0.0.1',
    created_at: '2026-09-22 08:00:00',
  },
  {
    id: 2,
    user_id: 1,
    actor_name: 'Tariq Al-Mansoor',
    action: 'employee_created',
    entity_type: 'employee',
    entity_id: 1,
    old_values: null,
    new_values: { employee_id: 'NDS-00001', name: 'Tariq Al-Mansoor', role: 'HR Director' },
    ip_address: '127.0.0.1',
    created_at: '2026-09-22 08:05:00',
  },
  {
    id: 3,
    user_id: 1,
    actor_name: 'Tariq Al-Mansoor',
    action: 'user_account_linked',
    entity_type: 'user',
    entity_id: 1,
    old_values: null,
    new_values: { user_id: 1, employee_id: 'NDS-00001' },
    ip_address: '127.0.0.1',
    created_at: '2026-09-22 08:06:00',
  },
  {
    id: 4,
    user_id: 1,
    actor_name: 'Tariq Al-Mansoor',
    action: 'employee_created',
    entity_type: 'employee',
    entity_id: 2,
    old_values: null,
    new_values: { employee_id: 'NDS-00002', name: 'Sarah Jenkins', role: 'Lead Software Architect' },
    ip_address: '127.0.0.1',
    created_at: '2026-09-22 08:12:00',
  },
  {
    id: 5,
    user_id: 1,
    actor_name: 'Administrator',
    action: 'role_permissions_updated',
    entity_type: 'role_matrix',
    entity_id: 0,
    old_values: null,
    new_values: { updated_roles: ['administrator', 'nds_hr_admin', 'nds_hr_manager', 'nds_hr_officer', 'nds_hr_employee'] },
    ip_address: '127.0.0.1',
    created_at: '2026-09-22 09:30:00',
  },
];

export const initialRoles: RoleMeta[] = [
  {
    slug: 'administrator',
    name: 'WordPress Administrator',
    description: 'Full access to WordPress administrative features and all HR modules.',
    is_system: true,
    assigned_users_count: 1,
  },
  {
    slug: 'nds_hr_admin',
    name: 'HR Administrator',
    description: 'Complete administrative control over all HR modules, roles, and settings.',
    is_system: false,
    assigned_users_count: 2,
  },
  {
    slug: 'nds_hr_manager',
    name: 'HR Manager',
    description: 'Workforce management, approvals, team operations, and audit review.',
    is_system: false,
    assigned_users_count: 3,
  },
  {
    slug: 'nds_hr_officer',
    name: 'HR Officer',
    description: 'Read-only administrative dashboard and directory access.',
    is_system: false,
    assigned_users_count: 2,
  },
  {
    slug: 'nds_hr_employee',
    name: 'Employee',
    description: 'Self-service portal access only. Blocked from wp-admin.',
    is_system: false,
    assigned_users_count: 85,
  },
];

export const initialCapabilityGroups: RoleCapabilityGroup[] = [
  {
    id: 'access',
    label: 'System Access',
    capabilities: [
      {
        slug: 'nds_hr_access_admin',
        label: 'Access HR Administration',
        description: 'Grant access to WordPress backend HR area (/wp-admin/)',
      },
      {
        slug: 'nds_hr_access_employee',
        label: 'Access Employee Self-Service',
        description: 'Grant access to frontend corporate portal (/employee/)',
      },
    ],
  },
  {
    id: 'employees',
    label: 'Employee Management',
    capabilities: [
      {
        slug: 'nds_hr_view_employees',
        label: 'View Employee Directory',
        description: 'Browse workforce member records and department assignments',
      },
      {
        slug: 'nds_hr_manage_employees',
        label: 'Create & Manage Employees',
        description: 'Create new employee files, toggle active statuses',
      },
      {
        slug: 'nds_hr_edit_employees',
        label: 'Edit Employee Records',
        description: 'Modify salary, job positions, and personal details',
      },
      {
        slug: 'nds_hr_delete_employees',
        label: 'Delete Employee Records',
        description: 'Permanently remove employee records and linked data',
      },
    ],
  },
  {
    id: 'departments',
    label: 'Organization & Structure',
    capabilities: [
      {
        slug: 'nds_hr_view_departments',
        label: 'View Departments & Designations',
        description: 'Read-only organizational hierarchy',
      },
      {
        slug: 'nds_hr_manage_departments',
        label: 'Manage Departments & Positions',
        description: 'Create and configure corporate departments and positions',
      },
    ],
  },
  {
    id: 'self_service',
    label: 'Self-Service Portal',
    capabilities: [
      {
        slug: 'nds_hr_view_own_profile',
        label: 'View Own Profile',
        description: 'View personal employment, position, and corporate details',
      },
      {
        slug: 'nds_hr_edit_own_profile',
        label: 'Edit Own Contact Details',
        description: 'Update phone number, address, and emergency contacts',
      },
    ],
  },
  {
    id: 'security',
    label: 'Administration & Security',
    capabilities: [
      {
        slug: 'nds_hr_view_audit_logs',
        label: 'View Audit & Compliance Logs',
        description: 'Inspect immutable records of all HR actions and changes',
      },
      {
        slug: 'nds_hr_manage_roles',
        label: 'Manage Roles & Permissions',
        description: 'Configure granular capability matrix across all system roles',
      },
      {
        slug: 'nds_hr_manage_settings',
        label: 'Manage Global Settings',
        description: 'Configure corporate parameters, email notifications, and policies',
      },
    ],
  },
  {
    id: 'attendance',
    label: 'Attendance (Future Foundation)',
    capabilities: [
      {
        slug: 'nds_hr_manage_attendance',
        label: 'Manage Company Attendance Records',
        description: 'Review and adjust workforce clock in/out times',
      },
      {
        slug: 'nds_hr_view_own_attendance',
        label: 'View Personal Attendance History',
        description: 'Check personal punch history and working hours',
      },
    ],
  },
  {
    id: 'leaves',
    label: 'Leave Management (Future Foundation)',
    capabilities: [
      {
        slug: 'nds_hr_manage_leaves',
        label: 'Manage Leave Types & Balances',
        description: 'Configure vacation quotas and annual balance carryover',
      },
      {
        slug: 'nds_hr_approve_leaves',
        label: 'Approve/Reject Leave Requests',
        description: 'Line manager and HR review workflow',
      },
      {
        slug: 'nds_hr_view_own_leaves',
        label: 'Submit & View Own Leaves',
        description: 'Employee request submission and balance balance review',
      },
    ],
  },
  {
    id: 'payroll',
    label: 'Payroll (Future Foundation)',
    capabilities: [
      {
        slug: 'nds_hr_manage_payroll',
        label: 'Process Payroll & Salary Sheets',
        description: 'Generate monthly payroll runs with allowances and deductions',
      },
      {
        slug: 'nds_hr_view_payroll',
        label: 'View Workforce Payroll Reports',
        description: 'Export salary summaries and bank transfer sheets',
      },
      {
        slug: 'nds_hr_view_own_payslips',
        label: 'View Personal Payslips',
        description: 'Self-service PDF payslip downloads for employees',
      },
    ],
  },
];

export const initialRoleMatrix: Record<string, Record<string, boolean>> = {
  administrator: {
    nds_hr_access_admin: true,
    nds_hr_access_employee: true,
    nds_hr_view_employees: true,
    nds_hr_manage_employees: true,
    nds_hr_edit_employees: true,
    nds_hr_delete_employees: true,
    nds_hr_view_departments: true,
    nds_hr_manage_departments: true,
    nds_hr_view_own_profile: true,
    nds_hr_edit_own_profile: true,
    nds_hr_view_audit_logs: true,
    nds_hr_manage_roles: true,
    nds_hr_manage_settings: true,
    nds_hr_manage_attendance: true,
    nds_hr_view_own_attendance: true,
    nds_hr_manage_leaves: true,
    nds_hr_approve_leaves: true,
    nds_hr_view_own_leaves: true,
    nds_hr_manage_payroll: true,
    nds_hr_view_payroll: true,
    nds_hr_view_own_payslips: true,
  },
  nds_hr_admin: {
    nds_hr_access_admin: true,
    nds_hr_access_employee: true,
    nds_hr_view_employees: true,
    nds_hr_manage_employees: true,
    nds_hr_edit_employees: true,
    nds_hr_delete_employees: true,
    nds_hr_view_departments: true,
    nds_hr_manage_departments: true,
    nds_hr_view_own_profile: true,
    nds_hr_edit_own_profile: true,
    nds_hr_view_audit_logs: true,
    nds_hr_manage_roles: true,
    nds_hr_manage_settings: true,
    nds_hr_manage_attendance: true,
    nds_hr_view_own_attendance: true,
    nds_hr_manage_leaves: true,
    nds_hr_approve_leaves: true,
    nds_hr_view_own_leaves: true,
    nds_hr_manage_payroll: true,
    nds_hr_view_payroll: true,
    nds_hr_view_own_payslips: true,
  },
  nds_hr_manager: {
    nds_hr_access_admin: true,
    nds_hr_access_employee: true,
    nds_hr_view_employees: true,
    nds_hr_manage_employees: true,
    nds_hr_edit_employees: true,
    nds_hr_delete_employees: false,
    nds_hr_view_departments: true,
    nds_hr_manage_departments: false,
    nds_hr_view_own_profile: true,
    nds_hr_edit_own_profile: true,
    nds_hr_view_audit_logs: true,
    nds_hr_manage_roles: false,
    nds_hr_manage_settings: false,
    nds_hr_manage_attendance: true,
    nds_hr_view_own_attendance: true,
    nds_hr_manage_leaves: false,
    nds_hr_approve_leaves: true,
    nds_hr_view_own_leaves: true,
    nds_hr_manage_payroll: false,
    nds_hr_view_payroll: true,
    nds_hr_view_own_payslips: true,
  },
  nds_hr_officer: {
    nds_hr_access_admin: true,
    nds_hr_access_employee: true,
    nds_hr_view_employees: true,
    nds_hr_manage_employees: false,
    nds_hr_edit_employees: false,
    nds_hr_delete_employees: false,
    nds_hr_view_departments: true,
    nds_hr_manage_departments: false,
    nds_hr_view_own_profile: true,
    nds_hr_edit_own_profile: true,
    nds_hr_view_audit_logs: false,
    nds_hr_manage_roles: false,
    nds_hr_manage_settings: false,
    nds_hr_manage_attendance: false,
    nds_hr_view_own_attendance: true,
    nds_hr_manage_leaves: false,
    nds_hr_approve_leaves: false,
    nds_hr_view_own_leaves: true,
    nds_hr_manage_payroll: false,
    nds_hr_view_payroll: false,
    nds_hr_view_own_payslips: true,
  },
  nds_hr_employee: {
    nds_hr_access_admin: false,
    nds_hr_access_employee: true,
    nds_hr_view_employees: false,
    nds_hr_manage_employees: false,
    nds_hr_edit_employees: false,
    nds_hr_delete_employees: false,
    nds_hr_view_departments: false,
    nds_hr_manage_departments: false,
    nds_hr_view_own_profile: true,
    nds_hr_edit_own_profile: true,
    nds_hr_view_audit_logs: false,
    nds_hr_manage_roles: false,
    nds_hr_manage_settings: false,
    nds_hr_manage_attendance: false,
    nds_hr_view_own_attendance: true,
    nds_hr_manage_leaves: false,
    nds_hr_approve_leaves: false,
    nds_hr_view_own_leaves: true,
    nds_hr_manage_payroll: false,
    nds_hr_view_payroll: false,
    nds_hr_view_own_payslips: true,
  },
};
